[package]
authors = ["Jorge Aparicio <jorge.aparicio@ferrous-systems.com>"]
edition = "2018"
name = "flip-lld"
version = "0.1.0"

[dependencies]
anyhow = "1.0.26"
walkdir = "2.3.1"
xmas-elf = "0.7.0"
